version: "3.3"
services:
  rstudio-server: 
    build: .
    environment:
      PASSWORD: helloworld
    ports:
      - 8787:8787
    volumes:
      - renv_docker:/renv/
      - .:/home/rstudio/Documents
volumes:
  renv_docker:

